#!/bin/bash
#SBATCH -o slurm_logs/resnet_200_verbs_full.sh.log-%j
#SBATCH --gres=gpu:volta:1

# Train baseline
# python fairness_cv_project/datasets/imSitu/model_training/train_resnet.py --dataset 200_verbs_full/train_val --save_folder 200_verbs_full/baseline/

# # Train CBM
# python fairness_cv_project/methods/label_free_cbm/src/train_cbm.py --dataset imSitu_200_full --backbone resnet50 --concept_set data/concept_sets/imSitu_200_filtered.txt --save_dir saved_models/imSitu/200_verbs_full/CBM/sparse_no_gender --interpretability_cutoff 0.3 --n_iters 80 --lam 0.007 --print

# # python fairness_cv_project/methods/label_free_cbm/src/train_cbm.py --dataset imSitu_200_full --backbone resnet50 --concept_set data/concept_sets/imSitu_200_filtered.txt --save_dir saved_models/imSitu/200_verbs_full/CBM/dense_no_gender --interpretability_cutoff 0.3 --n_iters 80 --print

# python fairness_cv_project/methods/label_free_cbm/src/train_cbm.py --dataset imSitu_200_full --backbone resnet50 --concept_set data/concept_sets/imSitu_200_gender.txt --save_dir saved_models/imSitu/200_verbs_full/CBM/sparse_gender --interpretability_cutoff 0.3 --n_iters 80 --lam 0.0007 --print --protected_concepts "a male" "a female"

# # python fairness_cv_project/methods/label_free_cbm/src/train_cbm.py --dataset imSitu_200_full --backbone resnet50 --concept_set data/concept_sets/imSitu_200_gender.txt --save_dir saved_models/imSitu/200_verbs_full/CBM/dense_gender --interpretability_cutoff 0.3 --n_iters 80 --print --protected_concepts "a male" "a female"

# # Test Baseline

# # python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --path_model saved_models/imSitu/200_verbs_full/baseline/model.pt --path_result results/imSitu/200_verbs_full/baseline --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt


# # Test CBM

# python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/200_verbs_full/CBM/sparse_no_gender/imSitu_200_full_imSitu_200_filtered  --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --path_result results/imSitu/200_verbs_full/CBM/sparse_no_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt

# # python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/200_verbs_full/CBM/dense_no_gender/imSitu_200_full_imSitu_200_filtered --path_result results/imSitu/200_verbs_full/CBM/dense_no_gender --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt


# python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/200_verbs_full/CBM/sparse_gender/imSitu_200_full_imSitu_200_gender --path_result results/imSitu/200_verbs_full/CBM/sparse_gender --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt


# # python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/200_verbs_full/CBM/dense_gender/imSitu_200_full_imSitu_200_gender --path_result results/imSitu/200_verbs_full/CBM/dense_gender --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt


# # Explainability

# python fairness_cv_project/methods/label_free_cbm/src/explainability.py --load_dir saved_models/imSitu/200_verbs_full/CBM/sparse_gender/imSitu_200_full_imSitu_200_gender --file_path results/imSitu/200_verbs_full/weights/sparse_gender.xlsx

# python fairness_cv_project/methods/label_free_cbm/src/explainability.py --load_dir saved_models/imSitu/200_verbs_full/CBM/dense_gender/imSitu_200_full_imSitu_200_gender --file_path results/imSitu/200_verbs_full/weights/dense_gender.xlsx

# python fairness_cv_project/methods/label_free_cbm/src/explainability.py --load_dir saved_models/imSitu/200_verbs_full/CBM/sparse_no_gender/imSitu_200_full_imSitu_200_filtered --file_path results/imSitu/200_verbs_full/weights/sparse_no_gender.xlsx

# python fairness_cv_project/methods/label_free_cbm/src/explainability.py --load_dir saved_models/imSitu/200_verbs_full/CBM/dense_no_gender/imSitu_200_full_imSitu_200_filtered --file_path results/imSitu/200_verbs_full/weights/dense_no_gender.xlsx

# python fairness_cv_project/methods/label_free_cbm/src/train_cbm.py --dataset imSitu_200_full --backbone resnet50 --concept_set data/concept_sets/imSitu_200_gender.txt --save_dir saved_models/imSitu/200_verbs_full/CBM/gender/ic0.3_lam_0.0007_cc0/ --interpretability_cutoff 0.3 --n_iters 80 --lam 0.0007 --clip_cutoff 0 --print ; python fairness_cv_project/methods/label_free_cbm/src/train_cbm.py --dataset imSitu_200_full --backbone resnet50 --concept_set data/concept_sets/imSitu_200_gender.txt --save_dir saved_models/imSitu/200_verbs_full/CBM/gender/ic0_lam_0.0007_cc0/ --interpretability_cutoff 0 --n_iters 80 --lam 0.0007 --clip_cutoff 0 --print ; python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/200_verbs_full/CBM/gender/ic0_lam_0.0007_cc0/imSitu_200_full_imSitu_200_gender --path_result results/imSitu/200_verbs_full/CBM/gender/ic0_lam_0.0007_cc0 --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt ; python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/200_verbs_full/CBM/gender/ic0.3_lam_0.0007_cc0/imSitu_200_full_imSitu_200_gender --path_result results/imSitu/200_verbs_full/CBM/gender/ic0.3_lam_0.0007_cc0 --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt


python fairness_cv_project/methods/label_free_cbm/src/train_cbm.py --dataset imSitu_200_full --backbone resnet50 --concept_set data/concept_sets/imSitu_200_extended.txt --save_dir saved_models/imSitu/cheatBM/200_verbs_full --interpretability_cutoff 0.0 --n_iters 80 --lam 0.0007 --clip_cutoff 0 --print 
# python fairness_cv_project/methods/label_free_cbm/src/train_cbm.py --dataset imSitu_200_balanced --backbone resnet50 --concept_set data/concept_sets/imSitu_200_extended.txt --save_dir saved_models/imSitu/cheatBM/200_verbs_balanced --interpretability_cutoff 0.0 --n_iters 80 --lam 0.0007 --clip_cutoff 0 --print 
# python fairness_cv_project/methods/label_free_cbm/src/train_cbm.py --dataset imSitu_200_imbalanced_1 --backbone resnet50 --concept_set data/concept_sets/imSitu_200_extended.txt --save_dir saved_models/imSitu/cheatBM/200_verbs_imbalanced_1 --interpretability_cutoff 0.0 --n_iters 80 --lam 0.0007 --clip_cutoff 0 --print 
# python fairness_cv_project/methods/label_free_cbm/src/train_cbm.py --dataset imSitu_200_imbalanced_2 --backbone resnet50 --concept_set data/concept_sets/imSitu_200_extended.txt --save_dir saved_models/imSitu/cheatBM/200_verbs_imbalanced_2 --interpretability_cutoff 0.0 --n_iters 80 --lam 0.0007 --clip_cutoff 0 --print 
python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/cheatBM/200_verbs_full/imSitu_200_full_imSitu_200_extended --path_result results/imSitu/cheatBM/200_verbs_full/ --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt 
# python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/cheatBM/200_verbs_balanced/imSitu_200_balanced_imSitu_200_extended --path_result results/imSitu/cheatBM/200_verbs_balanced/ --path_test_dataset data/datasets/imSitu/data/200_verbs/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt  
# python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/cheatBM/200_verbs_imbalanced_1/imSitu_200_imbalanced_1_imSitu_200_extended --path_result results/imSitu/cheatBM/200_verbs_imbalanced_1/ --path_test_dataset data/datasets/imSitu/data/200_verbs/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt  
# python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/cheatBM/200_verbs_imbalanced_2/imSitu_200_imbalanced_2_imSitu_200_extended --path_result results/imSitu/cheatBM/200_verbs_imbalanced_2/ --path_test_dataset data/datasets/imSitu/data/200_verbs/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt  



# python fairness_cv_project/methods/label_free_cbm/src/train_cbm.py --dataset imSitu_200_full --backbone resnet50 --concept_set data/concept_sets/imSitu_200_extended.txt --save_dir saved_models/imSitu/cheatBM/200_verbs_full --interpretability_cutoff 0.0 --n_iters 80 --lam 0.0007 --clip_cutoff 0 --print ; python fairness_cv_project/methods/label_free_cbm/src/train_cbm.py --dataset imSitu_200_balanced --backbone resnet50 --concept_set data/concept_sets/imSitu_200_extended.txt --save_dir saved_models/imSitu/cheatBM/200_verbs_balanced --interpretability_cutoff 0.0 --n_iters 80 --lam 0.0007 --clip_cutoff 0 --print ; python fairness_cv_project/methods/label_free_cbm/src/train_cbm.py --dataset imSitu_200_imbalanced_1 --backbone resnet50 --concept_set data/concept_sets/imSitu_200_extended.txt --save_dir saved_models/imSitu/cheatBM/200_verbs_imbalanced_1 --interpretability_cutoff 0.0 --n_iters 80 --lam 0.0007 --clip_cutoff 0 --print ; python fairness_cv_project/methods/label_free_cbm/src/train_cbm.py --dataset imSitu_200_imbalanced_2 --backbone resnet50 --concept_set data/concept_sets/imSitu_200_extended.txt --save_dir saved_models/imSitu/cheatBM/200_verbs_imbalanced_2 --interpretability_cutoff 0.0 --n_iters 80 --lam 0.0007 --clip_cutoff 0 --print ; python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/cheatBM/200_verbs_full/imSitu_200_full_imSitu_200_extended --path_result results/imSitu/cheatBM/200_verbs_full/ --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt ; python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/cheatBM/200_verbs_balanced/imSitu_200_balanced_imSitu_200_extended --path_result results/imSitu/cheatBM/200_verbs_balanced/ --path_test_dataset data/datasets/imSitu/data/200_verbs/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt ; python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/cheatBM/200_verbs_imbalanced_1/imSitu_200_imbalanced_1_imSitu_200_extended --path_result results/imSitu/cheatBM/200_verbs_imbalanced_1/ --path_test_dataset data/datasets/imSitu/data/200_verbs/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt ; python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/cheatBM/200_verbs_imbalanced_2/imSitu_200_imbalanced_2_imSitu_200_extended --path_result results/imSitu/cheatBM/200_verbs_imbalanced_2/ --path_test_dataset data/datasets/imSitu/data/200_verbs/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt  