#!/bin/bash
#SBATCH -o slurm_logs/train_final_layer.sh.log-%j
#SBATCH --gres=gpu:volta:1


# Train final layer

python fairness_cv_project/methods/label_free_cbm/src/train_final_layer.py --dataset imSitu_200_full --save_name 'CBM_imSitu_200_full/activation_imSitu_200_full'
python fairness_cv_project/methods/label_free_cbm/src/train_final_layer.py --dataset imSitu_200_balanced --save_name 'CBM_imSitu_200_full/activation_imSitu_200_balanced'
python fairness_cv_project/methods/label_free_cbm/src/train_final_layer.py --dataset imSitu_200_imbalanced_1 --save_name 'CBM_imSitu_200_full/activation_imSitu_200_imbalanced_1'
python fairness_cv_project/methods/label_free_cbm/src/train_final_layer.py --dataset imSitu_200_imbalanced_2 --save_name 'CBM_imSitu_200_full/activation_imSitu_200_imbalanced_2'
python fairness_cv_project/methods/label_free_cbm/src/train_final_layer.py --dataset imSitu_200_male --save_name 'CBM_imSitu_200_full/activation_imSitu_200_male'
python fairness_cv_project/methods/label_free_cbm/src/train_final_layer.py --dataset imSitu_200_female --save_name 'CBM_imSitu_200_full/activation_imSitu_200_female'

# Test final layer

python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/custom/CBM_imSitu_200_full/activation_imSitu_200_full --path_result results/imSitu/custom/CBM_imSitu_200_full/imSitu_200_full --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt
python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/custom/CBM_imSitu_200_full/activation_imSitu_200_balanced --path_result results/imSitu/custom/CBM_imSitu_200_full/imSitu_200_balanced --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt
python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/custom/CBM_imSitu_200_full/activation_imSitu_200_imbalanced_1 --path_result results/imSitu/custom/CBM_imSitu_200_full/imSitu_200_imbalanced_1 --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt
python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/custom/CBM_imSitu_200_full/activation_imSitu_200_imbalanced_2 --path_result results/imSitu/custom/CBM_imSitu_200_full/imSitu_200_imbalanced_2 --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt
python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/custom/CBM_imSitu_200_full/activation_imSitu_200_male --path_result results/imSitu/custom/CBM_imSitu_200_full/imSitu_200_male --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt
python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/custom/CBM_imSitu_200_full/activation_imSitu_200_female --path_result results/imSitu/custom/CBM_imSitu_200_full/imSitu_200_female --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt


python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/custom/CBM_imSitu_200_full/activation_imSitu_200_full --path_result results/imSitu/custom/CBM_imSitu_200_full/imSitu_200_full --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt ; python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/custom/CBM_imSitu_200_full/activation_imSitu_200_balanced --path_result results/imSitu/custom/CBM_imSitu_200_full/imSitu_200_balanced --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt ; python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/custom/CBM_imSitu_200_full/activation_imSitu_200_imbalanced_1 --path_result results/imSitu/custom/CBM_imSitu_200_full/imSitu_200_imbalanced_1 --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt ; python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/custom/CBM_imSitu_200_full/activation_imSitu_200_imbalanced_2 --path_result results/imSitu/custom/CBM_imSitu_200_full/imSitu_200_imbalanced_2 --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt ; python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/custom/CBM_imSitu_200_full/activation_imSitu_200_male --path_result results/imSitu/custom/CBM_imSitu_200_full/imSitu_200_male --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt ; python fairness_cv_project/datasets/imSitu/model_training/test_resnet.py --is_cbm --path_model saved_models/imSitu/custom/CBM_imSitu_200_full/activation_imSitu_200_female --path_result results/imSitu/custom/CBM_imSitu_200_full/imSitu_200_female --path_test_dataset data/datasets/imSitu/data/200_verbs_full/test_with_gender --num_classes 200 --path_list_verbs data/classes/imSitu_200_classes.txt